// Catalogue des codes de permission (module.ressource.action). Source de
// vérité TypeScript — miroir exact du seed dans
// supabase/migrations/0001_tenancy_rbac.sql. Toute permission ajoutée ici doit
// être ajoutée à la migration correspondante (voir docs/architecture/rbac.md).
export const PERMISSIONS = [
  "organization.manage",
  "organization.manage_members",
  "members.read",
  "members.write",
  "families.read",
  "families.write",
  "departments.read",
  "departments.write",
  "groups.read",
  "groups.write",
  "pastoral_care.read",
  "pastoral_care.write",
  "pastoral_appointments.read",
  "pastoral_appointments.write",
  "checkin.read",
  "checkin.write",
  "attendance.read",
  "attendance.write",
  "events.read",
  "events.write",
  "finance.accounts.read",
  "finance.accounts.write",
  "finance.transactions.read",
  "finance.transactions.write",
  "finance.expenses.read",
  "finance.expenses.write",
  "finance.expenses.approve",
  "donations.read",
  "donations.write",
  "budgets.read",
  "budgets.write",
  "budgets.approve",
  "notifications.read",
  "volunteers.read",
  "volunteers.write",
  "communications.read",
  "communications.write",
  "carpooling.read",
  "carpooling.participate",
  "carpooling.manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];
